### ISSUE TITLE
不支持图片转换

### ISSUE THREAD

**Issue by sojuo** [ayuanlmo/lmo-transform#7]
将图片导入后可以转换成视频格式，但无法转换成图片格式。

**Comment by ayuanlmo** [comment]
收到 将在后续进行修复

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: sojuo ***@***.***>
寄件日期: Friday, May 3, 2024 11:18:41 AM
收件者: ayuanlmo/lmo-transform ***@***.***>
副本: Subscribed ***@***.***>
主旨: [ayuanlmo/lmo-transform] 不支持图片转换 (Issue #7)


将图片导入后可以转换成视频格式，但无法转换成图片格式。

―
