### ISSUE TITLE
路径问题

### ISSUE THREAD

**Issue by SHIKEAIXY** [ayuanlmo/lmo-transform#8]
您好问一下这个视频转换后报错的路径默认存在哪里了？我点击窗口内的`打开文件夹`打开的是桌面，在这当中并未发现视频

**Comment by ayuanlmo** [comment]
在设置里面，有个设置输出路径的。也有默认路径

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: 小雨 ***@***.***>
寄件日期: Saturday, November 16, 2024 2:48:20 PM
收件者: ayuanlmo/lmo-transform ***@***.***>
副本: Subscribed ***@***.***>
主旨: [ayuanlmo/lmo-transform] 路径问题 (Issue #8)


您好问一下这个视频转换后报错的路径默认存在哪里了？我点击窗口内的打开文件夹打开的是桌面，在这当中并未发现视频

―
